LANE_WIDTH_M = 25
LANE_HEIGHT_M = 20
SPEED_LIMIT_MS = 25
LANE_LENGTH_M = 3000


LANE_LATERAL_KEY = "lateral"
LANE_LATERAL_PASSING_KEY = "lateral_passing"
LANE_VERTICAL_PASSING_KEY = "vertical_passing"

LANE_COLORS = {
    #light blue
    LANE_LATERAL_KEY: '#ADD8E6',
    LANE_LATERAL_PASSING_KEY: '#90EE90',
    LANE_VERTICAL_PASSING_KEY: '#FFFFE0'
}

